//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.0.30319.33440.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:schemas-upnp-org:device-1-0")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="urn:schemas-upnp-org:device-1-0", IsNullable=false)]
public partial class root {
    
    private rootSpecVersion specVersionField;
    
    private rootDevice deviceField;
    
    /// <remarks/>
    public rootSpecVersion specVersion {
        get {
            return this.specVersionField;
        }
        set {
            this.specVersionField = value;
        }
    }
    
    /// <remarks/>
    public rootDevice device {
        get {
            return this.deviceField;
        }
        set {
            this.deviceField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:schemas-upnp-org:device-1-0")]
public partial class rootSpecVersion {
    
    private sbyte majorField;
    
    private sbyte minorField;
    
    /// <remarks/>
    public sbyte major {
        get {
            return this.majorField;
        }
        set {
            this.majorField = value;
        }
    }
    
    /// <remarks/>
    public sbyte minor {
        get {
            return this.minorField;
        }
        set {
            this.minorField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:schemas-upnp-org:device-1-0")]
public partial class rootDevice {
    
    private string deviceTypeField;
    
    private string friendlyNameField;
    
    private string manufacturerField;
    
    private string manufacturerURLField;
    
    private string modelDescriptionField;
    
    private string modelNameField;
    
    private float modelNumberField;
    
    private string modelURLField;
    
    private long serialNumberField;
    
    private string uDNField;
    
    private int uPCField;
    
    private rootDeviceService[] serviceListField;
    
    private string presentationURLField;
    
    /// <remarks/>
    public string deviceType {
        get {
            return this.deviceTypeField;
        }
        set {
            this.deviceTypeField = value;
        }
    }
    
    /// <remarks/>
    public string friendlyName {
        get {
            return this.friendlyNameField;
        }
        set {
            this.friendlyNameField = value;
        }
    }
    
    /// <remarks/>
    public string manufacturer {
        get {
            return this.manufacturerField;
        }
        set {
            this.manufacturerField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="anyURI")]
    public string manufacturerURL {
        get {
            return this.manufacturerURLField;
        }
        set {
            this.manufacturerURLField = value;
        }
    }
    
    /// <remarks/>
    public string modelDescription {
        get {
            return this.modelDescriptionField;
        }
        set {
            this.modelDescriptionField = value;
        }
    }
    
    /// <remarks/>
    public string modelName {
        get {
            return this.modelNameField;
        }
        set {
            this.modelNameField = value;
        }
    }
    
    /// <remarks/>
    public float modelNumber {
        get {
            return this.modelNumberField;
        }
        set {
            this.modelNumberField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="anyURI")]
    public string modelURL {
        get {
            return this.modelURLField;
        }
        set {
            this.modelURLField = value;
        }
    }
    
    /// <remarks/>
    public long serialNumber {
        get {
            return this.serialNumberField;
        }
        set {
            this.serialNumberField = value;
        }
    }
    
    /// <remarks/>
    public string UDN {
        get {
            return this.uDNField;
        }
        set {
            this.uDNField = value;
        }
    }
    
    /// <remarks/>
    public int UPC {
        get {
            return this.uPCField;
        }
        set {
            this.uPCField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("service", IsNullable=false)]
    public rootDeviceService[] serviceList {
        get {
            return this.serviceListField;
        }
        set {
            this.serviceListField = value;
        }
    }
    
    /// <remarks/>
    public string presentationURL {
        get {
            return this.presentationURLField;
        }
        set {
            this.presentationURLField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:schemas-upnp-org:device-1-0")]
public partial class rootDeviceService {
    
    private string serviceTypeField;
    
    private string serviceIdField;
    
    private string controlURLField;
    
    private string eventSubURLField;
    
    private string sCPDURLField;
    
    /// <remarks/>
    public string serviceType {
        get {
            return this.serviceTypeField;
        }
        set {
            this.serviceTypeField = value;
        }
    }
    
    /// <remarks/>
    public string serviceId {
        get {
            return this.serviceIdField;
        }
        set {
            this.serviceIdField = value;
        }
    }
    
    /// <remarks/>
    public string controlURL {
        get {
            return this.controlURLField;
        }
        set {
            this.controlURLField = value;
        }
    }
    
    /// <remarks/>
    public string eventSubURL {
        get {
            return this.eventSubURLField;
        }
        set {
            this.eventSubURLField = value;
        }
    }
    
    /// <remarks/>
    public string SCPDURL {
        get {
            return this.sCPDURLField;
        }
        set {
            this.sCPDURLField = value;
        }
    }
}
